### ISSUE TITLE
Hi, Apocas

### ISSUE THREAD

**Issue by objcdeveloper** [apocas/node-whmcs#15]
Thank you for your node version of whmcs.

I just need to ask a question.

1. how can I install whmcs (npm isntall whmcs)?
          When I enter this, it says warning that there's no license.
2. var validConfig = {
  username: process.env.WHMCS_USER || 'username',
  password: process.env.WHMCS_KEY || 'password',
  apiKey: process.env.WHMCS_AK || 'accessKey',
  serverUrl: process.env.WHMCS_URL || 'http://192.168.1.1/includes/api.php'
};
Here what's username? admin user or whmcs register user(email)
Password: md5('password') is this right?
apiKey: Can you please tell me about this one in detail. Sorry I don't have much knowledge about this.

I'm asking for personal help. As a new nodejs and web developer, I don't know what to do.
So let's help together. Maybe I can be of great help to you in the future. No one knows

**Comment by apocas** [comment]
I don't see how it's possible the npm install to print a "there's no license error", check your package.json maybe.

Some of those questions are answered in the WHMCS documentation.

apiKey is only needed when IP based access restrictions are not being used in WHMCS security options.

Check the usage examples and the tests, they are very straight forward, just copy past them and you will get it started.
