### ISSUE TITLE
Help me!

### ISSUE THREAD

**Issue by objcdeveloper** [apocas/node-whmcs#17]
Hello. First of all, thank you for this project. I love it.
But I'm having problem with testing this one with my whmcs server.
I've already tested user name and password with php version which was provided by whmcs api documentation sample.
So for next step, I tried with your node project and it outputs error message.
       I downgraded my node version to 0.10.30 because with latest version, it says child_process:customFds ...deprecated, use stdio instead....

But with this 10.30, it also says Authentication Failed.
Is there any problem sending user credentials to the server?
Thank you.

**Comment by itscassa** [comment]
You have to enable the WHMCS for your IP and also have to create a user account that is in a role with API access.

Also make sure you md5 the password in the config.
