### ISSUE TITLE
New maintained repo

### ISSUE THREAD

**Issue by DamageESP** [apocas/node-whmcs#27]
Hey everyone!

I deeply modified this repo and adapted it to the new WHMCS auth system, using ES6 and all of that goodness.

If you want to check it out: [https://github.com/DamageESP/whmcs-js](https://github.com/DamageESP/whmcs-js)

Disclaimer: it's still a WIP and I'm still migrating a lot of the code. There is room for a lot of improvements. Any help, PRs, etc. are welcome.

**Comment by apocas** [comment]
Why not contributing with a pr?

**Comment by DamageESP** [comment]
Well, it seemed like this repo was no longer being maintained, so I decided to create my own and maintain it myself, now that I'm working on an app that will depend on it.

But yeah, if you are still around, I can always just make a PR.

**Comment by apocas** [comment]
Sure, I can even make you contributor :)
